/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "whatsapp": "#25D366",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#b3c5fd",
        "on-tertiary-fixed-variant": "#812800",
        "surface-container-low": "#f2f4f6",
        "primary-fixed": "#dae2ff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb59b",
        "secondary": "#4a5d8e",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#324575",
        "primary-fixed-dim": "#b2c5ff",
        "tertiary-container": "#a93802",
        "surface": "#f7f9fb",
        "on-primary-container": "#ccd8ff",
        "on-tertiary-container": "#ffcebd",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "outline": "#737785",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "on-primary": "#ffffff",
        "surface-tint": "#0056d2",
        "surface-container-high": "#e6e8ea",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#0040a1",
        "on-secondary": "#ffffff",
        "background": "#f7f9fb",
        "primary-container": "#0056d2",
        "tertiary-fixed": "#ffdbcf",
        "outline-variant": "#c3c6d6",
        "primary": "#0040a1",
        "on-secondary-container": "#3e5181",
        "surface-dim": "#d8dadc",
        "on-surface-variant": "#424654",
        "inverse-primary": "#b2c5ff",
        "on-primary-fixed": "#001847",
        "tertiary": "#822800",
        "surface-variant": "#e0e3e5",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#001847",
        "on-tertiary-fixed": "#380d00",
        "on-background": "#191c1e",
        "secondary-container": "#b3c5fd"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}