/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "whatsapp": "#25D366",
        "primary-fixed": "#dae1ff",
        "surface-container": "#e5eeff",
        "tertiary": "#58595f",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#0054d6",
        "on-tertiary-container": "#f8f7fe",
        "tertiary-fixed": "#e3e2e9",
        "tertiary-container": "#717177",
        "inverse-surface": "#213145",
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#f8f7ff",
        "primary": "#0050cb",
        "on-surface": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#b3c5ff",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#6cf8bb",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#1a1b20",
        "on-primary-fixed-variant": "#003fa4",
        "tertiary-fixed-dim": "#c7c6cd",
        "surface": "#f8f9ff",
        "inverse-primary": "#b3c5ff",
        "on-secondary-container": "#00714d",
        "surface-container-low": "#eff4ff",
        "secondary": "#006c49",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "primary-container": "#0066ff",
        "outline-variant": "#c2c6d8",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "outline": "#727687",
        "background": "#f8f9ff",
        "on-tertiary-fixed-variant": "#46464c",
        "error-container": "#ffdad6",
        "on-background": "#0b1c30",
        "on-surface-variant": "#424656",
        "on-primary-fixed": "#001849",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}